apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgCTDHunMo8x+QLSDYlF3DZcwwaJWguLO0sne29wfHV9M+GnGcjs+IEqDl6BYIOSnGzNwZSIdQS+MmEBaBRhWmhPC9kh52X2p4lqSnwznnkrplMEb0kICwocPvZkrI2wqSQkefQ1/jKVd/KLv03AZMCIz/UYxZ1J55eBykFsjK4ynanjv8GGWUN7YgcNv77lJ1AbtOvjIeLjd77eEpBEMxrpu0Flr3bpFLJ0gvOfbxIi7QHx+hN7ELfu4elCIFkzr9ZGdVuxHA5/4v6tfdCXteGCruJoeYmRe+SEoidDIkDepM98OGTdsxNXUM5D2b6ExiKdy/xoHx4f57/jhiQZzM7lKdxmVKRwEHpUfTWNt+lhixK0UhTfzt6DHIYtc3RMVvY2VhTqt+t1Dw+F3iNU5bIEtKDvvGm3qzSAiH202zh08PbzXZ9n1cicKQklIOqCMCyUDgSIjbnFAyv281YTyrjVWmFO67igDWonEDZb09grMN1GoHFA+88rzADZYsyhIu0vQFP+AwyV/14SuA0/8X5slqkGq6VQ4pAiLxrNwQuHjbQ/19y9snUyMt6TQqMMZY/XyVFt4vE7hFEPyq/LlUlqlW9FPbnxGsyPzrx5EWrJgXr4iAg/xlPy1xoCH+z5opMTtP/n0SZoefMrq2OICA6qrwfmvOieqsfHQTLB/0c0vcj/rNAkcwJdz5jzG5tMquxVFFvUt5ZX7Q==
    DB_USER: AgCEOh59afRSc3f5klSPBl/lAgrsxNQv7bFN2jxGgKziBY0DE2wi4alvKgX3iehQjUZ0AaLxMAMpxQ3Ndy8JBavhrbz4J38DktKnyH9+lR4YZ9V9TmvpHHkiZwZVyfgLkEzb1ME8WS6Eub40Hls1hR/prr1n2Nd7pZc/SXJM+NmoCqCetazKLGeNgDyKr4bitMVQTeYWqHEbPUG/m8CMyLL/R8CV2LMBM0JU6wFaHauS9sCSLYaGuaPIEdZOC+tj6Iz6S9ru/9Fmqn5u6G0WnFCtqhr0FhH2GbNZk4YJqtQjp2pFdR7ZKDupdFAeLhjB2982X3u/AJTGl1tpevxQ9UzstHDHZfgBQRO1gymNzhuAhU9YjIWmdCl5RDSj4Ax0Oy2uxcQQHgFfI7+t0nMQAPUsvDRHSyfJu+E+V/ENTgLdKd84zjDA7couCQ6yowjx5LQF4jJNtU7Xg8QB9vspdBCdiSK7qwl0OCcD8JGQ/Mv3RVZC6nJOAfxHAEVb8j2yotcNGfPaCzSZ2aap+H+UsOL8nsjvy6OxCH1zWTw2KG9wwKOuTT3ORo+rOLJSDTN0PzhIBPkIKxHekRoLubUNTZQFmy7ApsNI9IvqC0U0AuDd3gJz1HMiBfRtpmeTE3XC3CWyUNYveRr6w/NYnIWlGOOIpvDkBWK35wkrJKQa66CHkNshupJLqJnY6b++V2P7hbYrhuCDCylZPw==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

