apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgAATLwspFGdoFcjkVLqsjfrQriYhuVacLcVM4NsiZPDAE4cPoS6l8leieT1qTWVSoWtb2HlG8oQVQpPa079iu56dlLbvINLlzF3bB4Qw4M2gbRBk/NJBgqvcsD5GfughxG9KGgGqItFdZRsElefoyXo5KYlRbbwd9Z8x1w0qquUeBqD5ic1vq5zFzPE7NiQTHQSgXvyR2AJwuE7LB2VOGVgHRIh6bvHRZMv1D0GVxwEDUhHC5UXwzAgNaIktOc94ywiYUtm8IQOr+mvcuE9Wj1Mx71nQ0f2mL8lwRAgRbgVE71Q10jPeWFtRKkJ5DDUTT8YOHpjdWx6HROBrydlMYZefx9ynoXzhvBXmsEEIHJ75zxtgi7t2ZHGkg8ilhwGqpcPTqZYvxxknXjnaU/NoVybqORNyUd9e9V5/asqVZEaks/d/9KMEZJ1TgSqOfyyGX9f0RGpyXQq0Q7BuQuvfeGy/lnddpT4VI//TfbH8GMAxUVzzA9YQit4hCH595YvcISgiWJz1EdNNC59skJJJVAIyKw/DLujIUX4efAIk1SV8tejASUOM+T7C/0Udd1ysJBc7j2hI7BBuEGmaoDtvFMh5bPo9hY22rkYJBtbbBHFYjEWwS/LOi+3vv0ajv9nmY0Ay9I8Qdbl2cmFLy+hK7ozl4xzOGAc17O+9HxcyGg2ciajt5jwQJWisVl4fYW1kmzbOchm4jfWGQ==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque

